print("Welcome to the tip calculator!")
total = float(input("What was the total bill? "))
tip = float(input("What percentage tip would you like to give? "))
people = int(input("How many people to slip the bill? "))
final = round(total * (1+tip/100) / people, 2)
print(f"Each person should pay: ${final}")